### ISSUE TITLE
Task: Build some test scripts, perhaps using SmartBear

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/OGCAPI-EDR-Sprint2#19] opened 2020-11-09 23:35 UTC
> @ShaneMill1 will probably build some test scripts, perhaps using SmartBear, focussing on valid queries to keep a narrow scope.

In addition to test scripts, I will be in coordination with @m-burgoyne regarding implementations

_Originally posted by @ShaneMill1 in https://github.com/opengeospatial/OGCAPI-EDR-Sprint2/issues/1#issuecomment-722476782_

**Comment by ShaneMill1** [comment] 2020-11-10 14:25
This is a duplicate of #10 and can be closed (I can't close it)

**Closed as completed** 2020-11-10 15:10 UTC
